### ISSUE TITLE
Register Page doesn't let the user know that they need to enter "Province" in abbreviated format (example: Alberta -> AB)

### ISSUE THREAD

**Issue by CHZelaya** [CHZelaya/TravelExpertsWebApplication#30]
Potential Fix:

Add guidance for the user to properly input their province in abbreviations or change field to drop down list with abbreviations already populated.

**Comment by WARHE8D** [comment]
![image](https://github.com/user-attachments/assets/049f05c8-defc-4fa0-8a5b-f317b6ece875)
I have updated this in the latest commits this should fix it
